# Airflow + dbt Starter — Environment Variables
# Generated by GC Data Setup Wizard

# PostgreSQL
POSTGRES_USER=${postgres_user}
POSTGRES_PASSWORD=${postgres_password}
POSTGRES_DB=${postgres_db}
POSTGRES_PORT=${postgres_port}

# Adminer
ADMINER_PORT=${adminer_port}

# Airflow
AIRFLOW__CORE__FERNET_KEY=${airflow_fernet_key}
AIRFLOW__CORE__EXECUTOR=LocalExecutor
AIRFLOW__CORE__LOAD_EXAMPLES=False
AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${postgres_user}:${postgres_password_urlsafe}@postgres:5432/${postgres_db}
AIRFLOW__WEBSERVER__EXPOSE_CONFIG=False
AIRFLOW_ADMIN_USER=${airflow_admin_user}
AIRFLOW_ADMIN_PASSWORD=${airflow_admin_password}
AIRFLOW_WEBSERVER_PORT=${airflow_webserver_port}

# dbt
DBT_PROJECT_NAME=${dbt_project_name}
DBT_SCHEMA=${dbt_schema}
DBT_PROFILES_DIR=/opt/airflow/dbt