# Airflow + dbt Starter — Docker Compose
# Generated by GC Data Setup Wizard

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  volumes:
    - ./src/dags:/opt/airflow/dags
    - ./src/dbt:/opt/airflow/dbt
    - airflow-logs:/opt/airflow/logs
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:16-alpine
    container_name: starter-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${postgres_user}"
      POSTGRES_PASSWORD: "${postgres_password}"
      POSTGRES_DB: "${postgres_db}"
    ports:
      - "${postgres_port}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${postgres_user} -d ${postgres_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4-standalone
    container_name: starter-adminer
    restart: unless-stopped
    ports:
      - "${adminer_port}:8080"
    depends_on:
      postgres:
        condition: service_healthy

  airflow-init:
    <<: *airflow-common
    container_name: starter-airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users delete --username '${airflow_admin_user}' 2>/dev/null || true
        airflow users create \
          --username '${airflow_admin_user}' \
          --password '${airflow_admin_password}' \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@localhost
        echo "Init complete"
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    container_name: starter-airflow-webserver
    command: airflow webserver --port 8080
    ports:
      - "${airflow_webserver_port}:8080"
    restart: unless-stopped
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  airflow-scheduler:
    <<: *airflow-common
    container_name: starter-airflow-scheduler
    command: airflow scheduler
    restart: unless-stopped
    depends_on:
      airflow-init:
        condition: service_completed_successfully

volumes:
  postgres-data:
  airflow-logs:
